### ISSUE TITLE
Error in the middle of the training loop.

### ISSUE THREAD

**Issue by Mehrdad-AI** [cjy1992/interp-e2e-driving#16]
Hello
I have this error in the middle of the training loop and I do not know how to solve it. 
Thank you for guiding me.

WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 1430 (sensor.camera.rgb)
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 1532 (sensor.other.collision)
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 1533 (sensor.lidar.ray_cast)
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 1534 (sensor.camera.rgb)
2021-05-30 17:37:23.516593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-05-30 17:37:24.289861: W tensorflow/stream_executor/gpu/asm_compiler.cc:81] Running ptxas --version returned 256
2021-05-30 17:37:24.314032: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 256, output:
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
2021-05-30 17:38:19.059828: W tensorflow/core/framework/op_kernel.cc:1741] Unknown: AttributeError: module 'tensorflow' has no attribute 'logging'
Traceback (most recent call last):

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 90, in py_gif_summary
    image_summ.encoded_image_string = encode_gif(images[i], fps)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 46, in encode_gif
    proc = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 118, in py_gif_event
    summary = py_gif_summary(tag, tensor, max_outputs, fps)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 92, in py_gif_summary
    tf.logging.warning(

AttributeError: module 'tensorflow' has no attribute 'logging'

Traceback (most recent call last):
  File "train_eval.py", line 831, in <module>
    app.run(main)
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train_eval.py", line 825, in main
    train_eval(FLAGS.root_dir, FLAGS.experiment_name)
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "train_eval.py", line 711, in train_eval
    image_keys=input_names+mask_names)
  File "train_eval.py", line 216, in compute_summaries
    gif_summary('ObservationVideoEvalPolicy', images, 1, fps)
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 650, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  AttributeError: module 'tensorflow' has no attribute 'logging'
Traceback (most recent call last):

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 90, in py_gif_summary
    image_summ.encoded_image_string = encode_gif(images[i], fps)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 46, in encode_gif
    proc = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 118, in py_gif_event
    summary = py_gif_summary(tag, tensor, max_outputs, fps)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 92, in py_gif_summary
    tf.logging.warning(

AttributeError: module 'tensorflow' has no attribute 'logging'

[[{{node cond/then/_0/ObservationVideoEvalPolicy/PyFunc}}]]
  (1) Unknown:  AttributeError: module 'tensorflow' has no attribute 'logging'
Traceback (most recent call last):

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 90, in py_gif_summary
    image_summ.encoded_image_string = encode_gif(images[i], fps)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 46, in encode_gif
    proc = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/home/ai/anaconda3/envs/tensor/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 118, in py_gif_event
    summary = py_gif_summary(tag, tensor, max_outputs, fps)

  File "/media/ai/HDD/CARLA_0.9.6/PythonAPI/examples/interp-e2e-driving-master/interp_e2e_driving/utils/gif_utils.py", line 92, in py_gif_summary
    tf.logging.warning(

AttributeError: module 'tensorflow' has no attribute 'logging'

[[{{node cond/then/_0/ObservationVideoEvalPolicy/PyFunc}}]]
[[cond/output/_8/_10]]
0 successful operations.
0 derived errors ignored. [Op:__inference_gif_summary_v2_656643]

Function call stack:
gif_summary_v2 -> gif_summary_v2

**Comment by Mehrdad-AI** [comment]
This problem was solved with this command.
sudo apt update
sudo apt install ffmpeg
