### ISSUE TITLE
ValueError: unsupported datatype for array

### ISSUE THREAD

**Issue by Panshark** [cjy1992/interp-e2e-driving#26]
Hi @cjy1992 ,
I found this error when running `./run_train_eval.sh`. Does somebody know how to fix it? It would be very grateful if someone could help me. Thank you very much.
```
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/larx/gym/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
connecting to Carla server...
Carla server connected!
2023-02-04 17:26:17.182860: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
I0204 17:26:17.759369 140282135445696 common.py:923] No checkpoint available at logs/carla-v0/latent_sac/train
I0204 17:26:17.760652 140282135445696 common.py:923] No checkpoint available at logs/carla-v0/latent_sac/policy
I0204 17:26:17.761663 140282135445696 common.py:923] No checkpoint available at logs/carla-v0/latent_sac/replay_buffer
I0204 17:26:17.763702 140282135445696 train_eval.py:697] Initializing replay buffer by collecting experience for 1000 stepswith a random policy.
2023-02-04 17:26:22.341052: W tensorflow/core/framework/op_kernel.cc:1610] Invalid argument: ValueError: unsupported datatype for array

Traceback (most recent call last):

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 225, in _isolated_current_time_step_py
    return self._execute(_current_time_step_py)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 195, in _execute
    return fn(*args, **kwargs)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 221, in _current_time_step_py
    self._time_step = self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/batched_py_environment.py", line 130, in _reset
    return nest_utils.batch_nested_array(self._envs[0].reset())

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/wrappers.py", line 61, in _reset
    return self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/gym_wrapper.py", line 177, in _reset
    observation = self._gym_env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/R2L/interp-e2e-driving/interp-e2e-driving/interp_e2e_driving/environments/filter_observation_wrapper.py", line 40, in _reset
    observation = self._env.reset()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 260, in reset
    return self._get_obs()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 494, in _get_obs
    birdeye_surface = rgb_to_display_surface(birdeye, self.display_size)

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/misc.py", line 249, in rgb_to_display_surface
    pygame.surfarray.blit_array(surface, display)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/surfarray.py", line 81, in blit_array
    return numpysf.blit_array (surface, array)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/_numpysurfarray.py", line 82, in blit_array
    return array_to_surface(surface, array)

ValueError: unsupported datatype for array



2023-02-04 17:26:22.341125: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: ValueError: unsupported datatype for array

Traceback (most recent call last):

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 225, in _isolated_current_time_step_py
    return self._execute(_current_time_step_py)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 195, in _execute
    return fn(*args, **kwargs)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 221, in _current_time_step_py
    self._time_step = self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/batched_py_environment.py", line 130, in _reset
    return nest_utils.batch_nested_array(self._envs[0].reset())

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/wrappers.py", line 61, in _reset
    return self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/gym_wrapper.py", line 177, in _reset
    observation = self._gym_env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/R2L/interp-e2e-driving/interp-e2e-driving/interp_e2e_driving/environments/filter_observation_wrapper.py", line 40, in _reset
    observation = self._env.reset()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 260, in reset
    return self._get_obs()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 494, in _get_obs
    birdeye_surface = rgb_to_display_surface(birdeye, self.display_size)

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/misc.py", line 249, in rgb_to_display_surface
    pygame.surfarray.blit_array(surface, display)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/surfarray.py", line 81, in blit_array
    return numpysf.blit_array (surface, array)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/_numpysurfarray.py", line 82, in blit_array
    return array_to_surface(surface, array)

ValueError: unsupported datatype for array



         [[{{node current_time_step/current_time_step_py_func}}]]
         [[driver_loop/body/_1/StatefulPartitionedCall_2/StatefulPartitionedCall/while/body/_385/PartitionedFunctionCall/FloorMod/ReadVariableOp/_118]]
2023-02-04 17:26:22.341317: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: ValueError: unsupported datatype for array

Traceback (most recent call last):

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 225, in _isolated_current_time_step_py
    return self._execute(_current_time_step_py)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 195, in _execute
    return fn(*args, **kwargs)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 221, in _current_time_step_py
    self._time_step = self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/batched_py_environment.py", line 130, in _reset
    return nest_utils.batch_nested_array(self._envs[0].reset())

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/wrappers.py", line 61, in _reset
    return self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/gym_wrapper.py", line 177, in _reset
    observation = self._gym_env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/R2L/interp-e2e-driving/interp-e2e-driving/interp_e2e_driving/environments/filter_observation_wrapper.py", line 40, in _reset
    observation = self._env.reset()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 260, in reset
    return self._get_obs()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 494, in _get_obs
    birdeye_surface = rgb_to_display_surface(birdeye, self.display_size)

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/misc.py", line 249, in rgb_to_display_surface
    pygame.surfarray.blit_array(surface, display)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/surfarray.py", line 81, in blit_array
    return numpysf.blit_array (surface, array)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/_numpysurfarray.py", line 82, in blit_array
    return array_to_surface(surface, array)

ValueError: unsupported datatype for array



         [[{{node current_time_step/current_time_step_py_func}}]]
Traceback (most recent call last):
  File "train_eval.py", line 831, in <module>
    app.run(main)
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "train_eval.py", line 825, in main
    train_eval(FLAGS.root_dir, FLAGS.experiment_name)
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "train_eval.py", line 698, in train_eval
    initial_collect_driver.run()
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 526, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  ValueError: unsupported datatype for array

Traceback (most recent call last):

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 225, in _isolated_current_time_step_py
    return self._execute(_current_time_step_py)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 195, in _execute
    return fn(*args, **kwargs)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 221, in _current_time_step_py
    self._time_step = self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/batched_py_environment.py", line 130, in _reset
    return nest_utils.batch_nested_array(self._envs[0].reset())

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/wrappers.py", line 61, in _reset
    return self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/gym_wrapper.py", line 177, in _reset
    observation = self._gym_env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/R2L/interp-e2e-driving/interp-e2e-driving/interp_e2e_driving/environments/filter_observation_wrapper.py", line 40, in _reset
    observation = self._env.reset()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 260, in reset
    return self._get_obs()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 494, in _get_obs
    birdeye_surface = rgb_to_display_surface(birdeye, self.display_size)

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/misc.py", line 249, in rgb_to_display_surface
    pygame.surfarray.blit_array(surface, display)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/surfarray.py", line 81, in blit_array
    return numpysf.blit_array (surface, array)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/_numpysurfarray.py", line 82, in blit_array
    return array_to_surface(surface, array)

ValueError: unsupported datatype for array



         [[node current_time_step/current_time_step_py_func (defined at /home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
         [[driver_loop/body/_1/StatefulPartitionedCall_2/StatefulPartitionedCall/while/body/_385/PartitionedFunctionCall/FloorMod/ReadVariableOp/_118]]
  (1) Invalid argument:  ValueError: unsupported datatype for array

Traceback (most recent call last):

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 225, in _isolated_current_time_step_py
    return self._execute(_current_time_step_py)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 195, in _execute
    return fn(*args, **kwargs)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/tf_py_environment.py", line 221, in _current_time_step_py
    self._time_step = self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/batched_py_environment.py", line 130, in _reset
    return nest_utils.batch_nested_array(self._envs[0].reset())

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/wrappers.py", line 61, in _reset
    return self._env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/gym_wrapper.py", line 177, in _reset
    observation = self._gym_env.reset()

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tf_agents/environments/py_environment.py", line 141, in reset
    self._current_time_step = self._reset()

  File "/home/larx/R2L/interp-e2e-driving/interp-e2e-driving/interp_e2e_driving/environments/filter_observation_wrapper.py", line 40, in _reset
    observation = self._env.reset()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 260, in reset
    return self._get_obs()

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/carla_env.py", line 494, in _get_obs
    birdeye_surface = rgb_to_display_surface(birdeye, self.display_size)

  File "/home/larx/R2L/interp-e2e-driving/gym-carla/gym_carla/envs/misc.py", line 249, in rgb_to_display_surface
    pygame.surfarray.blit_array(surface, display)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/surfarray.py", line 81, in blit_array
    return numpysf.blit_array (surface, array)

  File "/home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/pygame/_numpysurfarray.py", line 82, in blit_array
    return array_to_surface(surface, array)

ValueError: unsupported datatype for array



         [[node current_time_step/current_time_step_py_func (defined at /home/larx/anaconda3/envs/e2e/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_run_1623]

Function call stack:
run -> run

  In call to configurable 'train_eval' (<function train_eval at 0x7f930f79c9d8>)
```

**Comment by David-Randolph** [comment]
I upgrade pygame and fix it.
